# Generated by Django 3.1.7 on 2021-03-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JsonDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreoperation', models.CharField(max_length=256)),
                ('entreprise', models.CharField(max_length=256)),
                ('annee_de_livraison', models.CharField(max_length=256)),
                ('ville', models.CharField(max_length=256)),
                ('mandataire', models.CharField(max_length=256)),
                ('ppi', models.CharField(max_length=256)),
                ('lycee', models.CharField(max_length=256)),
                ('notification_du_marche', models.CharField(max_length=256)),
                ('codeuai', models.CharField(max_length=256, unique=True)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=17)),
                ('etat_d_avancement', models.CharField(max_length=256)),
                ('montant_des_ap_votes_en_meu', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cao_attribution', models.CharField(max_length=256)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=17)),
                ('maitrise_d_oeuvre', models.CharField(max_length=256)),
                ('mode_de_devolution', models.CharField(max_length=256)),
                ('annee_d_individualisation', models.CharField(max_length=256)),
                ('enveloppe_prev_en_meu', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
