# Generated by Django 3.1.7 on 2021-03-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPI_API', '0003_auto_20210314_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondataset',
            name='nombre_de_lots',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
