# Generated by Django 3.1.7 on 2021-03-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPI_API', '0004_jsondataset_nombre_de_lots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondataset',
            name='annee_d_individualisation',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='jsondataset',
            name='annee_de_livraison',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='jsondataset',
            name='cao_attribution',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='jsondataset',
            name='codeuai',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='jsondataset',
            name='entreprise',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='jsondataset',
            name='enveloppe_prev_en_meu',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='jsondataset',
            name='etat_d_avancement',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='jsondataset',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
        migrations.AlterField(
            model_name='jsondataset',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
        migrations.AlterField(
            model_name='jsondataset',
            name='lycee',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='jsondataset',
            name='maitrise_d_oeuvre',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='jsondataset',
            name='mandataire',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='jsondataset',
            name='mode_de_devolution',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='jsondataset',
            name='montant_des_ap_votes_en_meu',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='jsondataset',
            name='nombre_de_lots',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='jsondataset',
            name='notification_du_marche',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='jsondataset',
            name='ppi',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='jsondataset',
            name='titreoperation',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='jsondataset',
            name='ville',
            field=models.CharField(max_length=256),
        ),
    ]
